"""Training algorithms with notebook state isolated per training session.

The numerical operations and update/selection order match the recorded notebook.
``image_numel`` defaults to 784; it also permits small synthetic CPU checks.
"""
import copy
import csv
import hashlib
import json
import math
import time
from contextlib import nullcontext
from pathlib import Path
import torch
from torch import nn
from torch.nn import functional as F
from .checkpoints import load_state_dict

bce = F.binary_cross_entropy_with_logits


def load_training_state(path, map_location='cpu'):
    """Restore a trusted local state generated by this training process.

    Full optimizer/RNG resume files are not the plain released model weights.
    PyTorch 2.6 changed torch.load's default, so select this behavior explicitly.
    """
    try:
        return torch.load(path, map_location=map_location, weights_only=False)
    except TypeError:
        return torch.load(path, map_location=map_location)

@torch.no_grad()
def update_parameter_average(averaged_model, raw_model, decay=0.999):
    if not 0 <= decay < 1:
        raise ValueError('EMA decay must be in [0, 1)')
    raw_parameters = dict(raw_model.named_parameters())
    for (name, value) in averaged_model.named_parameters():
        value.mul_(decay).add_(raw_parameters[name], alpha=1 - decay)
    raw_buffers = dict(raw_model.named_buffers())
    for (name, value) in averaged_model.named_buffers():
        value.copy_(raw_buffers[name])

def _initial_weights_fingerprint(state_dict):
    digest = hashlib.sha256()
    for name in sorted(state_dict):
        value = state_dict[name].detach().cpu().contiguous()
        digest.update(name.encode('utf-8'))
        digest.update(str(value.dtype).encode('ascii'))
        digest.update(str(tuple(value.shape)).encode('ascii'))
        digest.update(value.numpy().tobytes())
    return digest.hexdigest()

class TrainingSession:

    def __init__(self, config, val_loader, device, output_dir):
        self.config = copy.deepcopy(config)
        self.val_loader = val_loader
        self.device = torch.device(device)
        self.output_dir = Path(output_dir)
        self.image_numel = int(config.get('image_numel', 784))
        self.history = []
        self.training_summary = {}

    @torch.no_grad()
    def evaluate(self, model, loader):
        model.eval()
        values = []
        for batch in loader:
            x = batch[0].to(self.device, non_blocking=True)
            logits = model.logits(x).float()
            values.append(bce(logits, x, reduction='none').flatten(1).sum(1).cpu())
        nll = torch.cat(values).double()
        mean = nll.mean().item()
        return (dict(n=len(nll), nll_nats_per_image=mean, bce_nats_per_pixel=mean / self.image_numel, bits_per_pixel=mean / (self.image_numel * math.log(2)), standard_error=nll.std(unbiased=True).item() / math.sqrt(len(nll))), nll)

    def train(self, dataloader, model, optimizer, epochs, *, output_dir=None, resume=False):
        output_dir = self.output_dir if output_dir is None else Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=self.config['epochs'], eta_min=self.config['min_lr'])
        scaler = torch.cuda.amp.GradScaler(enabled=self.device.type == 'cuda')
        if resume:
            state = load_training_state(output_dir / 'training_state.pt', map_location=self.device)
            model.load_state_dict(state['model'])
            optimizer.load_state_dict(state['optimizer'])
            scheduler.load_state_dict(state['scheduler'])
            scaler.load_state_dict(state['scaler'])
            dataloader.generator.set_state(state['shuffle_rng'].cpu())
            torch.set_rng_state(state['torch_rng'].cpu())
            if self.device.type == 'cuda':
                torch.cuda.set_rng_state_all([s.cpu() for s in state['cuda_rng']])
            self.history = state['history']
            (initial, best, best_epoch) = (state['initial'], state['best'], state['best_epoch'])
            first_epoch = state['epoch'] + 1
            prior_seconds = state['training_seconds']
        else:
            self.history = []
            (best, best_epoch, first_epoch, prior_seconds) = (float('inf'), 0, 1, 0.0)
            (initial, _) = self.evaluate(model, self.val_loader)
            print(f'Parameters: {sum((p.numel() for p in model.parameters())):,}')
            print(f"Initial validation NLL: {initial['nll_nats_per_image']:.4f}", flush=True)
        training_start = time.perf_counter()
        for epoch in range(first_epoch, epochs + 1):
            start = time.perf_counter()
            model.train()
            (loss_sum, seen) = (0.0, 0)
            lr = optimizer.param_groups[0]['lr']
            for (x, labels) in dataloader:
                x = x.to(self.device, non_blocking=True)
                optimizer.zero_grad(set_to_none=True)
                with torch.cuda.amp.autocast() if self.device.type == 'cuda' else nullcontext():
                    loss = bce(model.logits(x), x)
                if not torch.isfinite(loss):
                    raise RuntimeError('Nonfinite training loss')
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                nn.utils.clip_grad_norm_(model.parameters(), self.config['grad_clip'])
                scaler.step(optimizer)
                scaler.update()
                loss_sum += loss.item() * len(x)
                seen += len(x)
            (val, _) = self.evaluate(model, self.val_loader)
            record = dict(epoch=epoch, train_bce=loss_sum / seen, train_nll=loss_sum / seen * self.image_numel, val_bce=val['bce_nats_per_pixel'], val_nll=val['nll_nats_per_image'], lr=lr, seconds=time.perf_counter() - start, train_images_seen=seen)
            assert seen == self.config['n_train']
            self.history.append(record)
            if record['val_nll'] < best:
                (best, best_epoch) = (record['val_nll'], epoch)
                torch.save({k: v.detach().cpu() for (k, v) in model.state_dict().items()}, output_dir / 'pixelcnn_best.pt')
            if epoch in (1, 5, 10, 25, 50, 75, 100):
                torch.save({k: v.detach().cpu() for (k, v) in model.state_dict().items()}, output_dir / f'pixelcnn_epoch_{epoch:02d}.pt')
            scheduler.step()
            elapsed = prior_seconds + time.perf_counter() - training_start
            state = dict(model=model.state_dict(), optimizer=optimizer.state_dict(), scheduler=scheduler.state_dict(), scaler=scaler.state_dict(), shuffle_rng=dataloader.generator.get_state(), torch_rng=torch.get_rng_state(), cuda_rng=torch.cuda.get_rng_state_all() if self.device.type == 'cuda' else [], history=self.history, initial=initial, best=best, best_epoch=best_epoch, epoch=epoch, training_seconds=elapsed)
            torch.save(state, output_dir / 'training_state.pt')
            with (output_dir / 'history.csv').open('w', newline='', encoding='utf-8') as f:
                writer = csv.DictWriter(f, fieldnames=list(record))
                writer.writeheader()
                writer.writerows(self.history)
            (output_dir / 'training_progress.json').write_text(json.dumps(dict(best_epoch=best_epoch, best_val_nll=best, completed_epoch=epoch, initial_validation=initial, training_seconds=elapsed), indent=2))
            print(f"Epoch {epoch:03d}/{self.config['epochs']}: train NLL={record['train_nll']:.3f}, val NLL={record['val_nll']:.3f}, lr={lr:.6f}, {record['seconds']:.1f}s", flush=True)
        elapsed = prior_seconds + time.perf_counter() - training_start
        model.load_state_dict(load_state_dict(output_dir / 'pixelcnn_best.pt'))
        self.training_summary = dict(best_epoch=best_epoch, best_val_nll=best, initial_validation=initial, training_seconds=elapsed, parameter_count=sum((p.numel() for p in model.parameters())))
        (output_dir / 'training_summary.json').write_text(json.dumps(self.training_summary, indent=2))
        return [row['train_bce'] for row in self.history]

    def train_finetuning(self, dataloader, model, optimizer, max_epochs, output_dir, initial_state_dict, resume=False):
        """Warm-start weights and select initial, raw, or EMA by validation NLL.

    A finished run is restored without additional training. The optional
    self.config['pause_after_epoch'] stops at a complete-epoch checkpoint without
    marking the run finished; it is useful for checking interrupted execution.
    """
        if max_epochs < 1:
            raise ValueError('max_epochs must be positive')
        if dataloader.generator is None:
            raise ValueError('Use an explicit DataLoader generator for exact resume')
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        decay = float(self.config.get('ema_decay', 0.999))
        patience = int(self.config.get('early_stop_patience', 5))
        min_delta = float(self.config.get('early_stop_min_delta', 0.02))
        if not 0 <= decay < 1 or patience < 1 or min_delta < 0:
            raise ValueError('Invalid averaging or early-stop settings')
        scheduler_settings = dict(mode='min', factor=float(self.config.get('plateau_factor', 0.5)), patience=int(self.config.get('plateau_patience', 2)), threshold=float(self.config.get('plateau_threshold', 0.02)), threshold_mode='abs', min_lr=float(self.config.get('min_lr', 1e-05)))
        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, **scheduler_settings)
        scaler = torch.cuda.amp.GradScaler(enabled=self.device.type == 'cuda')
        averaged_model = copy.deepcopy(model).eval()
        for parameter in averaged_model.parameters():
            parameter.requires_grad_(False)
        settings = dict(initial_weights_sha256=_initial_weights_fingerprint(initial_state_dict), channels=model.vertical_input.out_channels // 2, n_blocks=len(model.blocks), dilations=list(model.dilations), dropout_p=model.dropout_p, ema_decay=decay, early_stop_patience=patience, early_stop_min_delta=min_delta, max_epochs=int(max_epochs), scheduler=scheduler_settings, initial_lr=[group['lr'] for group in optimizer.param_groups], optimizer=optimizer.__class__.__name__, optimizer_defaults=copy.deepcopy(optimizer.defaults), batch_size=dataloader.batch_size, grad_clip=float(self.config.get('grad_clip', 1.0)), n_train=self.config['n_train'], n_val=self.config['n_val'], seed=self.config.get('seed'), split_seed=self.config.get('split_seed'), threshold=self.config.get('threshold'))
        history_fields = ['epoch', 'train_bce', 'train_nll', 'val_nll', 'raw_val_nll', 'ema_val_nll', 'lr', 'seconds', 'train_images_seen', 'val_source']
        best_path = output_dir / 'pixelcnn_best.pt'
        state_path = output_dir / 'training_state.pt'

        def save_best(chosen):
            torch.save({name: value.detach().cpu() for (name, value) in chosen.state_dict().items()}, best_path)

        def write_history():
            with (output_dir / 'history.csv').open('w', newline='', encoding='utf-8') as file:
                writer = csv.DictWriter(file, fieldnames=history_fields)
                writer.writeheader()
                writer.writerows(self.history)
        if resume:
            state = load_training_state(state_path, map_location=self.device)
            assert state['settings'] == settings, 'Fine-tuning configuration or initial weights changed'
            model.load_state_dict(state['model'])
            averaged_model.load_state_dict(state['ema_model'])
            optimizer.load_state_dict(state['optimizer'])
            scheduler.load_state_dict(state['scheduler'])
            scaler.load_state_dict(state['scaler'])
            dataloader.generator.set_state(state['shuffle_rng'].cpu())
            torch.set_rng_state(state['torch_rng'].cpu())
            if self.device.type == 'cuda':
                torch.cuda.set_rng_state_all([value.cpu() for value in state['cuda_rng']])
            self.history = state['history']
            initial = state['initial']
            (best, best_epoch, best_source) = (state['best'], state['best_epoch'], state['best_source'])
            (significant_best, bad_epochs) = (state['significant_best'], state['bad_epochs'])
            completed = state['epoch']
            (successful_steps, attempted_steps) = (state['successful_steps'], state['attempted_steps'])
            prior_seconds = state['training_seconds']
            (finished, stop_reason) = (state['finished'], state['stop_reason'])
        else:
            model.load_state_dict(initial_state_dict)
            averaged_model.load_state_dict(initial_state_dict)
            (initial, _) = self.evaluate(model, self.val_loader)
            assert initial['n'] == self.config['n_val']
            if 'initial_val_nll' in self.config:
                assert abs(initial['nll_nats_per_image'] - self.config['initial_val_nll']) < 1e-05
            best = significant_best = initial['nll_nats_per_image']
            scheduler.step(best)
            (best_epoch, best_source, bad_epochs, completed) = (0, 'initial', 0, 0)
            (successful_steps, attempted_steps, prior_seconds) = (0, 0, 0.0)
            (finished, stop_reason) = (False, 'running')
            initial_train = self.config.get('initial_train_nll')
            initial_bce = initial_train / self.config.get('image_numel', self.image_numel) if initial_train is not None else None
            self.history = [dict(epoch=0, train_bce=initial_bce, train_nll=initial_train, val_nll=best, raw_val_nll=best, ema_val_nll=best, lr=0.0, seconds=0.0, train_images_seen=0, val_source='initial')]
            save_best(model)
            write_history()
            print(f'Fine-tuning initial validation NLL: {best:.6f}', flush=True)
        training_start = time.perf_counter()

        def save_state():
            elapsed = prior_seconds + time.perf_counter() - training_start
            state = dict(model=model.state_dict(), ema_model=averaged_model.state_dict(), optimizer=optimizer.state_dict(), scheduler=scheduler.state_dict(), scaler=scaler.state_dict(), settings=settings, shuffle_rng=dataloader.generator.get_state(), torch_rng=torch.get_rng_state(), cuda_rng=torch.cuda.get_rng_state_all() if self.device.type == 'cuda' else [], history=self.history, initial=initial, best=best, best_epoch=best_epoch, best_source=best_source, significant_best=significant_best, bad_epochs=bad_epochs, epoch=completed, training_seconds=elapsed, max_epochs=max_epochs, successful_steps=successful_steps, attempted_steps=attempted_steps, finished=finished, stop_reason=stop_reason)
            torch.save(state, state_path)
            (output_dir / 'training_progress.json').write_text(json.dumps(dict(completed_epoch=completed, best_epoch=best_epoch, best_source=best_source, best_val_nll=best, significant_best=significant_best, bad_epochs=bad_epochs, successful_steps=successful_steps, attempted_steps=attempted_steps, finished=finished, stop_reason=stop_reason, training_seconds=elapsed), indent=2))
            return elapsed
        last_elapsed = prior_seconds
        if not resume:
            last_elapsed = save_state()
        if not finished:
            for epoch in range(completed + 1, max_epochs + 1):
                epoch_start = time.perf_counter()
                model.train()
                (loss_sum, seen, pixels_per_image) = (0.0, 0, None)
                lr = optimizer.param_groups[0]['lr']
                for batch in dataloader:
                    images = batch[0].to(self.device, non_blocking=True)
                    if pixels_per_image is None:
                        pixels_per_image = images[0].numel()
                    assert images[0].numel() == pixels_per_image
                    optimizer.zero_grad(set_to_none=True)
                    with torch.cuda.amp.autocast() if self.device.type == 'cuda' else nullcontext():
                        loss = F.binary_cross_entropy_with_logits(model.logits(images), images)
                    if not torch.isfinite(loss):
                        raise RuntimeError('Nonfinite fine-tuning loss')
                    scaler.scale(loss).backward()
                    scaler.unscale_(optimizer)
                    nn.utils.clip_grad_norm_(model.parameters(), settings['grad_clip'])
                    previous_scale = scaler.get_scale()
                    scaler.step(optimizer)
                    scaler.update()
                    attempted_steps += 1
                    if scaler.get_scale() >= previous_scale:
                        successful_steps += 1
                        update_parameter_average(averaged_model, model, decay)
                    loss_sum += loss.item() * len(images)
                    seen += len(images)
                assert seen == self.config['n_train']
                (raw_validation, _) = self.evaluate(model, self.val_loader)
                (ema_validation, _) = self.evaluate(averaged_model, self.val_loader)
                assert raw_validation['n'] == ema_validation['n'] == self.config['n_val']
                raw_value = raw_validation['nll_nats_per_image']
                ema_value = ema_validation['nll_nats_per_image']
                if not math.isfinite(raw_value) or not math.isfinite(ema_value):
                    raise RuntimeError('Nonfinite validation NLL')
                (value, source) = (raw_value, 'raw') if raw_value <= ema_value else (ema_value, 'ema')
                if value < best:
                    (best, best_epoch, best_source) = (value, epoch, source)
                    save_best(model if source == 'raw' else averaged_model)
                if significant_best - value > min_delta:
                    (significant_best, bad_epochs) = (value, 0)
                else:
                    bad_epochs += 1
                record = dict(epoch=epoch, train_bce=loss_sum / seen, train_nll=loss_sum / seen * pixels_per_image, val_nll=value, raw_val_nll=raw_value, ema_val_nll=ema_value, lr=lr, seconds=time.perf_counter() - epoch_start, train_images_seen=seen, val_source=source)
                self.history.append(record)
                completed = epoch
                if epoch == 1:
                    torch.save({name: value.detach().cpu() for (name, value) in model.state_dict().items()}, output_dir / 'pixelcnn_epoch_01.pt')
                scheduler.step(value)
                finished = bad_epochs >= patience or completed >= max_epochs
                stop_reason = 'early_stop' if bad_epochs >= patience else 'max_epochs' if completed >= max_epochs else 'running'
                pause_after = self.config.get('pause_after_epoch')
                if not finished and pause_after is not None and (completed >= pause_after):
                    stop_reason = 'paused'
                write_history()
                last_elapsed = save_state()
                print(f"Fine-tuning {epoch:02d}/{max_epochs}: train NLL={record['train_nll']:.6f}, raw val={raw_value:.6f}, EMA val={ema_value:.6f}, best={best:.6f} ({best_source}), lr={lr:.6g}, {record['seconds']:.1f}s", flush=True)
                if finished or stop_reason == 'paused':
                    break
        elapsed = last_elapsed
        assert len(self.history) - 1 == completed
        model.load_state_dict(load_state_dict(best_path))
        model.eval()
        self.training_summary = dict(best_epoch=best_epoch, best_source=best_source, best_val_nll=best, initial_validation=initial, completed_epochs=completed, max_epochs=max_epochs, finished=finished, stop_reason=stop_reason, training_seconds=elapsed, ema_decay=decay, dropout_p=model.dropout_p, parameter_count=sum((value.numel() for value in model.parameters())), successful_steps=successful_steps, attempted_steps=attempted_steps, successful_step_fraction=successful_steps / attempted_steps if attempted_steps else 1.0)
        (output_dir / 'training_summary.json').write_text(json.dumps(self.training_summary, indent=2))
        return self.training_summary
